### ISSUE TITLE
Make the module truly systemless

### ISSUE THREAD

**Issue by linuxandria** [Magisk-Modules-Repo/NFCScreenOff#1]
There is absolutely no reason you should be directly modifying a system partition with a _magisk module_, which on some devices isn't even possible (eg EROFS, dynamic partitions, or ext4 dedup).

This could have serious implications for SafetyNet and is much harder to revert if something goes wrong m

If magic mount is for some strange reasons not able to replace the APK, you're doing something wrong.

In your module, copy the APK to $MODDIR/system/app/NfcCi/NfcCi.apk (sorry if the name is incorrect) and magisk will handle it correctly for you! Modifying an APK after post-fs-data stage is also inadvisable. 

Have you tested relying solely on magic mount?

I eagerly await your response!

**Comment by lapwat** [comment]
Great to hear your feedback.

Yes it has been tested with magic mount already.

Sadly, the only way I could make it work was by:
1. Mounting the original APK
2. Let NFCService
3. Replace the original APK with the modded APK
4. Restart NFCService by killing its process

I was surprised I could do that but I cannot think about a better idea. Are you thinking about implementing security fixes that will prevent this behavior?

**Comment by linuxandria** [comment]
So do you actually inject the APK into /system or do you just bund mount it at a convenient time?
Have you tried letting magisk do the mount, and just restarting the NFC service in service.d scripts?

**Comment by linuxandria** [comment]
Have you considered not using the standard module structure so as not to let magisk do the bind mount, but do it yourself in service.sh? After a restart, it'd achieve the same effect, and be truly systemless (and work on more devices therefore)

**Comment by linuxandria** [comment]
Eg put the APK in $MODDIR/NfcCi/NfcCi.apk
Then on service.sh:
`mount --bind $MODDIR/NfcCi/ /system/app/NfcCi`

Exact syntax may be incorrect but should do the trick.

Let me know if it works!

**Comment by lapwat** [comment]
I succeeded to use the mount --bind method:
https://github.com/Magisk-Modules-Repo/NFCScreenOff/commit/945a22311b0e9e554e67bde58e229f805ca26705

Does it satisfy your requirements?

**Comment by linuxandria** [comment]
> I succeeded to use the mount --bind method:
> https://github.com/Magisk-Modules-Repo/NFCScreenOff/commit/945a22311b0e9e554e67bde58e229f805ca26705
> 
> Does it satisfy your requirements?
> 
> EDIT: Still does not work if I don't load original APK beforehand...

Have you tried inserting like a 10sec delay then bind mounting?

Rn I'm on a device your original wouldn't work - OnePlus 7t, so dynamic partitions + ext4 dedup

**Comment by lapwat** [comment]
Yes, I have tried those 4 combinations:
- mount original apk, wait 10 seconds, mount modded apk
- don't wait, mount modded apk
- wait 10 seconds, mount modded apk
- wait 20 seconds, mount modded apk

**Comment by lapwat** [comment]
Can we consider that the module is systemless now that I used the mount command ?

**Comment by linuxandria** [comment]
If it works 100% without needing to mess with /system ofc it is
