### ISSUE TITLE
Lost contactless option after install on mi11

### ISSUE THREAD

**Issue by aviranak** [Magisk-Modules-Repo/NfcScreenOff#10]
Hello. I tried installing this on mi 11 and now lost contactless payment option.

I tried flashing new rom and delete data. Nothing helped. Contactless payment is gone. Anything I can do to get it back?

Please help.

**Comment by lapwat** [comment]
I am sorry for your loss. I don't think it is possible that it is related to this module. If you uninstall this module you should get at the same point as before you installed it.

Try to flash VENDOR before new ROM.

**Comment by aviranak** [comment]
I'll try. Thanks for the fast response.

I didn't manage to uninstall the module because right after I installed it. My device got stuck and didn't boot after hard restart.
Than I flashed new eu rom and deleted data. It still not back. I'll try to flash before like you said. Thank you.
________________________________

**Comment by lapwat** [comment]
I suggest you read the [Help section](https://github.com/Magisk-Modules-Repo/NfcScreenOff#help-section) before you delete all your data.
