### ISSUE TITLE
return 404 when uploading apk

### ISSUE THREAD

**Issue by sonj2u** [Magisk-Modules-Repo/NfcScreenOff#11]
[magisk_install_log_2021-04-25T15:52:07Z.log](https://github.com/Magisk-Modules-Repo/NfcScreenOff/files/6371549/magisk_install_log_2021-04-25T15.52.07Z.log)

**Comment by sonj2u** [comment]
Sorry, I didn't make it clear, I'll add to it.

**Comment by lapwat** [comment]
Ok it was a mistake on my side. The patcher somehow needed to be relaunched. All good now.

Can you try again and close the issue if it works?

**Comment by sonj2u** [comment]
It works. Thank you. ☺️
