### ISSUE TITLE
Doesn't seem to work on OnePlus 5T (Pie)

### ISSUE THREAD

**Issue by Shaxine** [Magisk-Modules-Repo/NfcScreenOff#12]
**Describe the bug**
Module seems to install successfully (logs bellow) but NFC only works when screen is on.
Tried uninstall and reinstall as per the _Help Section_.

**Magisk logs at installation**
[magisk_install_log_2021-06-12T13-20-56Z.log](https://github.com/Magisk-Modules-Repo/NfcScreenOff/files/6642205/magisk_install_log_2021-06-12T13-20-56Z.log)

**Smartphone**
- Device: OnePlus 5T (OnePlus A5010)
- Android version: 9 Pie (9.0.11)
- ROM: OxygenOS (OOS)

**Comment by lapwat** [comment]
What can of tag are you trying to read ?

**Comment by Shaxine** [comment]
A programmable NFC Tag (ISO 14443-3A) Module: NXP MIFARE Ultralight - NTAG213
Works fine with Tasker (when screen is on)

**Comment by lapwat** [comment]
Can you try again and tell if it works?

**Comment by lapwat** [comment]
If it still does not work, please post the logs, they should be different.

**Comment by Shaxine** [comment]
I Removed it and installed again, but unfortunately it still doesn't work when the screen is off I tried with a different kind of tag as well.

You can find the new logs here: [magisk_install_log_2021-06-18T18:56:58Z.log](https://gist.githubusercontent.com/Shaxine/31953acdd0c9ed1f0e8d29a0711df0cb/raw/0a7da97fdb7a34590fa25a7fdb0fe2174856af96/magisk_install_log_2021-06-18T18:56:58Z.log)

**Comment by lapwat** [comment]
Ok it seems that the odex strategy is not properly working. Does your device make a sound when you scan a tag?

**Comment by lapwat** [comment]
I have updated the patcher, can you try again? I am sorry but I cannot test this odex strategy with my device, so it is going to be trial and error until we make it work.

Good news is that this strategy does not depend of the device. This means that you can still make Nfc Screen Off work if you install another ROM (lineage, crdoird, rr, xtended, ...).

**Comment by Shaxine** [comment]
Never heard a sound when scanning a tag (most of the time my phone is muted)

I tried again and the installation failed: [magisk_install_log_2021-06-19T07:11:43Z.log](https://gist.githubusercontent.com/Shaxine/b431bfb676d689a7ce1064f2f80a38c5/raw/4400b08de688147f76fec58691c1be4b2a5778ba/magisk_install_log_2021-06-19T07:11:43Z.log)

Tried a second time with the same result

**Comment by lapwat** [comment]
Hello can you try again, after reading your logs it seems that it's an issue with your `curl` command.
