### ISSUE TITLE
certificate problem: certificate has expired

### ISSUE THREAD

**Issue by Sv7en** [Magisk-Modules-Repo/NfcScreenOff#14]
- Copying zip to temp directory
- Installing NFC_Screen_Off-v0.3.2(32).zip
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
****************
 NFC Screen Off 
 by lapwat 
****************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
*******************
 Powered by Magisk 
*******************
- Extracting module files
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: README.md
   creating: bin/
  inflating: bin/curl
  inflating: bin/zip
  inflating: customize.sh
  inflating: module.prop
  inflating: service.sh
   creating: system/
  inflating: system/placeholder
-- Searching for NFC app in /system/app/ and /system/system_ext/app/ folders...
-- NfcNci.apk found!
-- Device info --
APK_NAME=NfcNci
MANUFACTURER=OnePlus
MODEL=ONEPLUS A5010
DEVICE=OnePlus5T
ROM=
-----------------
-- Searching for NfcNci.apk backup...
-- NfcNci_bak.apk not found. Creating backup of original NfcNci.apk.
-- Searching for NfcNci.odex backup...
-- NfcNci_bak.odex not found. Creating backup of original NfcNci.odex.
-- Searching for NfcNci.vdex backup...
-- NfcNci_bak.vdex not found. Creating backup of original NfcNci.vdex.
-- Searching for custom NfcNci.apk in extracted files...
-- NfcNci_align.apk not found.
-- Zipping NfcNci.apk and device's framework (/data/adb/modules_update/NFCScreenOff/bin/zip)
  adding: .env (deflated 5%)
  adding: NfcNci.apk (deflated 59%)
  adding: framework-res.apk (deflated 73%)
-- Uploading device's apks for modding (/data/adb/modules_update/NFCScreenOff/bin/curl), it may take a while (12Mb)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:08 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:11 --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
-- Classic modding failed, trying odex strategy
-- Adding whole framework folder and odex/vdex files to archive
  adding: .env (deflated 4%)
  adding: NfcNci.apk (deflated 59%)
  adding: NfcNci.odex (deflated 66%)
  adding: NfcNci.vdex (deflated 52%)
  adding: arm64/ (stored 0%)
  adding: arm64/boot-ext.vdex (deflated 9%)
  adding: arm64/boot-voip-common.oat (deflated 79%)
  adding: arm64/boot-telephony-ext.art (deflated 88%)
  adding: arm64/boot-framework-atb-backward-compatibility.art (deflated 94%)
  adding: arm64/boot-voip-common.art (deflated 34%)
  adding: arm64/boot-ims-common.vdex (deflated 7%)
  adding: arm64/boot-framework.vdex (deflated 64%)
  adding: arm64/boot-telephony-ext.vdex (deflated 14%)
  adding: arm64/boot-framework-atb-backward-compatibility.oat (deflated 95%)
  adding: arm64/boot-ims-common.art (deflated 38%)
  adding: arm64/boot-telephony-common.art (deflated 34%)
  adding: arm64/boot-org.ifaa.android.manager.vdex (deflated 23%)
  adding: arm64/boot-WfdCommon.oat (deflated 92%)
  adding: arm64/boot-ims-common.oat (deflated 89%)
  adding: arm64/boot-telephony-common.oat (deflated 67%)
  adding: arm64/boot-WfdCommon.art (deflated 76%)
  adding: arm64/boot-org.ifaa.android.manager.oat (deflated 93%)
  adding: arm64/boot-framework-atb-backward-compatibility.vdex (deflated 29%)
  adding: arm64/boot-org.ifaa.android.manager.art (deflated 90%)
  adding: arm64/boot-framework.oat (deflated 60%)
  adding: arm64/boot-framework.art (deflated 32%)
  adding: arm64/boot-WfdCommon.vdex (deflated 12%)
  adding: arm64/boot-ext.oat (deflated 64%)
  adding: arm64/boot-voip-common.vdex (deflated 19%)
  adding: arm64/boot-ext.art (deflated 28%)
  adding: arm64/boot-telephony-ext.oat (deflated 93%)
  adding: arm64/boot-telephony-common.vdex (deflated 17%)
/dev/tmp
-- Uploading archive for odex modding (/data/adb/modules_update/NFCScreenOff/bin/curl), it may take a while (8Mb)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
!! Odex strategy failed.
! Installation failed

**Comment by lapwat** [comment]
I think it was a DNS issue, can you try again ?

**Comment by VergeDX** [comment]
Okay, now this works for me : )
