### ISSUE TITLE
How to make the file work/run

### ISSUE THREAD

**Issue by Niloc133** [Magisk-Modules-Repo/NfcScreenOff#16]
Hey

I have downloaded the file but I dont know how to run/make the file work.

How can I solve this problem?

Greets,
Colin

**Comment by Jon8RFC** [comment]
It's a Magisk module.  It will only work when installed via Magisk:
https://www.xda-developers.com/how-to-install-magisk/

**Comment by lapwat** [comment]
Like Jon said, you have to:

- Root your phone
- Install Magisk
- Install NFCScreenOff from Magisk application

Happy to answer your questions
