### ISSUE TITLE
NFC is not working If the screen is locked 

### ISSUE THREAD

**Issue by aaref1234** [Magisk-Modules-Repo/NFCScreenOff#18]
I installed the module and turned on NFC and tried to buy with the bank card but the purchase does not happen and the screen is off or locked .

Galaxy Note 9
Android 10

**Comment by aaref1234** [comment]
This is the link to the app used in purchase :

https://play.google.com/store/apps/details?id=com.mada.madapay

**Comment by Jon8RFC** [comment]
It looks like "tap to pay when screen is off" is no longer a feature as of v0.3.2:
https://forum.xda-developers.com/t/module-nfc-screen-off.4034903/
