### ISSUE TITLE
I want NFC Tagged sound...

### ISSUE THREAD

**Issue by xmen06** [Magisk-Modules-Repo/NFCScreenOff#19]
I want NFC Tagged sound... Please keep a option to select it while installing the magisk module

**Comment by lapwat** [comment]
Not sure how to do that, can you open a PR ?

Alternatively, you can download this module and edit 2 lines in the file customize.sh:

https://github.com/Magisk-Modules-Repo/NfcScreenOff/blob/master/customize.sh#L87
https://github.com/Magisk-Modules-Repo/NfcScreenOff/blob/master/customize.sh#L96

Change `https://patcher.lapw.at` to `https://patcherwithsound.lapw.at`, zip the folder and install it via magisk.
