### ISSUE TITLE
Could not find a smali folder

### ISSUE THREAD

**Issue by Marcus4242** [Magisk-Modules-Repo/NfcScreenOff#2]
Hi,
thanks for providing this module - it is exactly what I was looking for :)
However, it is not working on my OnePlus One with a Lineage Bacon Android 9 custom ROM. NFC stops working all together (regardless of the screen being on or off). Event the NFC icon in the launcher is gone, when your service replacement kicks in.
Is there anything I can do to fix this?
Best,
Marcus

**Comment by lapwat** [comment]
Hello,

I have found the error. For some NFC apks, the disassembling process does not produce any smali files that are needed to reverse engineer the app.

I have updated the module to raise that error. I will try to find a solution in the mean time.

**Comment by lapwat** [comment]
@Marcus4242 Does the error still occur?

**Comment by DoganM95** [comment]
> @Marcus4242 Does the error still occur?

Yes, the smali folder error still occurs.
Tested today on version 0.2.0.

**Comment by lapwat** [comment]
Can you provide the Magisk logs please?

**Comment by DoganM95** [comment]
- Copying zip to temp directory
- Installing NFC_Screen_Off-v0.2.0(20).zip
- Current boot slot: _b
- Device is system-as-root
Archive:  /data/user/0/com.SbJPK93.va.Y.w.Y/cache/flash/install.zip
  inflating: module.prop
****************
 NFC Screen Off 
 by lapwat 
****************
*******************
 Powered by Magisk 
*******************
Archive:  /data/user/0/com.SbJPK93.va.Y.w.Y/cache/flash/install.zip
  inflating: customize.sh
- Extracting module files
Archive:  /data/user/0/com.SbJPK93.va.Y.w.Y/cache/flash/install.zip
  inflating: .gitignore
  inflating: README.md
  inflating: customize.sh
  inflating: module.prop
  inflating: service.sh
   creating: system/
  inflating: system/placeholder
-- Searching for NFC app in /system/app/ folder...
-- NfcNci.apk found!
-- Device info --
MANUFACTURER=Google
MODEL=Pixel 3 XL
DEVICE=crosshatch
ROM=
APK_NAME=NfcNci
-----------------
-- Searching for NfcNci.apk backup...
-- NfcNci_bak.apk found! Copying backup to the module update folder.
-- Searching for custom NfcNci.apk in extracted files...
-- NfcNci_align.apk not found.
-- Zipping NfcNci.apk and device's framework
update-binary: /data/adb/modules_update/NFCScreenOff/customize.sh: line 66: zip: not found
-- Uploading device's apks for modding (~15Mb)
update-binary: /data/adb/modules_update/NFCScreenOff/customize.sh: line 70: curl: not found
!! Could not find a smali folder while disassembling NfcNci.apk.
! Installation failed

**Comment by lapwat** [comment]
Weird it's written Pixel 3 XL in the logs.

Anyway, try installing `busybox` in Magisk and try reinstalling the module afterwards. It seems that magisk does not find zip/curl commands.

**Comment by DoganM95** [comment]
tried that already, no luck unfortunately

**Comment by lapwat** [comment]
Sorry to hear that.

I don't think I can help you with this error. It seems that it comes from zip/curl not being available at the time of installation.

Don't hesitate to come back and give your solution when you have found it because [you are not the only one](https://forum.xda-developers.com/showpost.php?p=82392615&postcount=38).

**Comment by DoganM95** [comment]
Alright, i did it.

- Copying zip to temp directory - Installing NFC_Screen_Off-v0.2.0(20).zip - Current boot slot: _b - Device is system-as-root Archive: /data/user/0/com.SbJPK93.va.Y.w.Y/cache/flash/install.zip inflating: module.prop **************** NFC Screen Off by lapwat **************** ******************* Powered by Magisk ******************* Archive: /data/user/0/com.SbJPK93.va.Y.w.Y/cache/flash/install.zip inflating: customize.sh - Extracting module files Archive: /data/user/0/com.SbJPK93.va.Y.w.Y/cache/flash/install.zip inflating: .gitignore inflating: README.md inflating: customize.sh inflating: module.prop inflating: service.sh creating: system/ inflating: system/placeholder -- Searching for NFC app in /system/app/ folder... -- NfcNci.apk found! -- Device info -- MANUFACTURER=Google MODEL=Pixel 3 XL DEVICE=crosshatch ROM= APK_NAME=NfcNci ----------------- -- Searching for NfcNci.apk backup... -- NfcNci_bak.apk found! Copying backup to the module update folder. -- Searching for custom NfcNci.apk in extracted files... -- NfcNci_align.apk not found. -- Zipping NfcNci.apk and device's framework adding: .env (stored 0%) adding: NfcNci.apk (deflated 20%) adding: framework-res.apk (deflated 65%) -- Uploading device's apks for modding (~15Mb) % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 3 16.3M 0 0 3 512k 0 980k 0:00:17 --:--:-- 0:00:17 978k 11 16.3M 0 0 11 1920k 0 1255k 0:00:13 0:00:01 0:00:12 1255k 17 16.3M 0 0 17 2944k 0 1162k 0:00:14 0:00:02 0:00:12 1162k 23 16.3M 0 0 23 3968k 0 1121k 0:00:14 0:00:03 0:00:11 1121k 29 16.3M 0 0 29 4928k 0 1088k 0:00:15 0:00:04 0:00:11 1088k 35 16.3M 0 0 35 5952k 0 1075k 0:00:15 0:00:05 0:00:10 1085k 41 16.3M 0 0 41 6912k 0 1056k 0:00:15 0:00:06 0:00:09 995k 47 16.3M 0 0 47 7936k 0 1051k 0:00:15 0:00:07 0:00:08 995k 53 16.3M 0 0 53 8960k 0 1050k 0:00:15 0:00:08 0:00:07 1000k 59 16.3M 0 0 59 9920k 0 1041k 0:00:16 0:00:09 0:00:07 998k 65 16.3M 0 0 65 10.6M 0 1039k 0:00:16 0:00:10 0:00:06 998k 71 16.3M 0 0 71 11.6M 0 1038k 0:00:16 0:00:11 0:00:05 1014k 77 16.3M 0 0 77 12.6M 0 1032k 0:00:16 0:00:12 0:00:04 1002k 83 16.3M 0 0 83 13.6M 0 1030k 0:00:16 0:00:13 0:00:03 997k 89 16.3M 0 0 89 14.5M 0 1025k 0:00:16 0:00:14 0:00:02 996k 95 16.3M 0 0 95 15.5M 0 1026k 0:00:16 0:00:15 0:00:01 998k 100 16.3M 0 0 100 16.3M 0 1012k 0:00:16 0:00:16 --:--:-- 953k 100 16.3M 0 0 100 16.3M 0 920k 0:00:18 0:00:18 --:--:-- 673k 100 16.3M 0 0 100 16.3M 0 872k 0:00:19 0:00:19 --:--:-- 493k 100 16.3M 0 0 100 16.3M 0 828k 0:00:20 0:00:20 --:--:-- 324k 100 16.3M 0 0 100 16.3M 0 789k 0:00:21 0:00:21 --:--:-- 143k 100 16.3M 0 0 100 16.3M 0 754k 0:00:22 0:00:22 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 721k 0:00:23 0:00:23 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 691k 0:00:24 0:00:24 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 664k 0:00:25 0:00:25 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 638k 0:00:26 0:00:26 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 615k 0:00:27 0:00:27 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 593k 0:00:28 0:00:28 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 573k 0:00:29 0:00:29 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 554k 0:00:30 0:00:30 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 536k 0:00:31 0:00:31 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 519k 0:00:32 0:00:32 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 504k 0:00:33 0:00:33 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 489k 0:00:34 0:00:34 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 475k 0:00:35 0:00:35 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 462k 0:00:36 0:00:36 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 449k 0:00:37 0:00:37 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 438k 0:00:38 0:00:38 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 426k 0:00:39 0:00:39 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 416k 0:00:40 0:00:40 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 406k 0:00:41 0:00:41 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 396k 0:00:42 0:00:42 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 387k 0:00:43 0:00:43 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 378k 0:00:44 0:00:44 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 370k 0:00:45 0:00:45 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 362k 0:00:46 0:00:46 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 354k 0:00:47 0:00:47 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 347k 0:00:48 0:00:48 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 340k 0:00:49 0:00:49 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 333k 0:00:50 0:00:50 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 326k 0:00:51 0:00:51 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 320k 0:00:52 0:00:52 --:--:-- 0 100 16.3M 0 0 100 16.3M 0 314k 0:00:53 0:00:53 --:--:-- 0 94 17.6M 24 318k 100 16.3M 6086 312k 0:03:35 0:00:53 0:02:42 76276 100 17.6M 100 1278k 100 16.3M 24308 311k 0:00:53 0:00:53 --:--:-- 354k -- Downloaded custom NfcNci.apk from lapwat's servers - Replace target: /system/app/NfcNci - Done

**Comment by DoganM95** [comment]
Seems like zip and curl were not installed in /system/bin and busybox doesn't seem to provide these packages. A solution would be to include **curl** and **zip** into your app and let the app copy them to /system/bin as magisk should be running as superuser if i am not mistaken.

never done app development, so just my suggestion.

**Comment by lapwat** [comment]
What is your solution?

**Comment by DoganM95** [comment]
My solution is adding **curl** and **zip** manually to /system/bin and starting the installation of NfcScreenOff afterwards.

So just copy the two binaries of the attached zip file:
[curl_and_zips.zip](https://github.com/Magisk-Modules-Repo/NfcScreenOff/files/4569469/curl_and_zips.zip) into for example the root of your repository and copy the two files like:

`cp ./{curl,zip} /system/bin`

before any installation begins. this way you are providing the applets which busybox doesn't but are necessary to install NfcScreenOff correctly.
