### ISSUE TITLE
Mirpay

### ISSUE THREAD

**Issue by evgehae** [Magisk-Modules-Repo/NFCScreenOff#20]
Здравствуйте,имеется два телефона ,первый mi 9lite андроид 11 ,на нем модуль работает исправно и стабильно ,второй redmi note 10 pro андроид 12, здесь модуль ломает платежную систему ,а точнее приложения оплаты ,сообщают ,что устройство рутировано ,или же разблокировано ,как можно исправить эту формальность?

English

Hello, there are two phones, the first mi 9lite android 11 on it the module works properly and stably, the second redmi note 10 pro android 12, here the module breaks the payment system, specifically the payment application, reported that the device is rooted, or unlocked, as you can fix this technicality?

**Comment by lapwat** [comment]
Please translate your message in english.

**Comment by lapwat** [comment]
I do not think that the phone reported as rooted is related to the installation of this module. You should take a look at **Magisk Hide** and **how to change the fingerprint of your phone**.

Please reply in English.
