### ISSUE TITLE
Server down and/or Pixel 7 compatibility

### ISSUE THREAD

**Issue by Jon8RFC** [Magisk-Modules-Repo/NFCScreenOff#21]
Thanks for this great module!

I haven't used it in a few months since I haven't updated my phone.  Now, with the Pixel 7 Pro, it's failing partially due to server error.  I don't know if that's known or not, and/or if the new Pixel or Android 13 has changes causing problems.

[magisk_install_log_2022-10-13T17.21.50.log](https://github.com/Magisk-Modules-Repo/NfcScreenOff/files/9781033/magisk_install_log_2022-10-13T17.21.50.log)

What else can I do to help?

**Comment by lapwat** [comment]
I am going to ask several files from your phone to try to understand why those exceptions arose:

- NfcNci.apk (should be in /system/app/NfcNci/ folder)
- /system/framework/framework-res.apk

**Comment by lapwat** [comment]
Alternatively, you can try to run the server yourself => https://gitlab.com/lapwat/nfcscreenoffpatcher

There is a Dockerfile and an HTTP app listening to port 8000.

Edit the two lines in `customize.sh` where `https://patcher.lapw.at` appears and replace it by `http://localhost:8000`.

**Comment by Jon8RFC** [comment]
For others searching:
Lapwat has dug into it and updated for the android changes. It's now working with my pixel 7 pro on Android 13. 

I suggest you one plus and other users give it another go!

Thank you, lapwat!
