### ISSUE TITLE
Bootloop

### ISSUE THREAD

**Issue by aptxyz** [Magisk-Modules-Repo/NFCScreenOff#3]
Successful installation
i am able to unlock device, however after 10~15s it rebooted into recovery twrp

Android Version: 9
Rom: Redmi/begonia/begonia:9/PPR1.180610.011/V11.0.3.0.PGGCNXM
Device: Redmi Note 8 Pro (China)

www.mediafire.com/file/zp83a75pl3y8k7n/NQNfcNci.apk/file
www.mediafire.com/file/f1yeted65mdei8a/framework-res.apk/file

Appreciate the help.

**Comment by lapwat** [comment]
This is because I could not disassemble your apk properly. See #2

**Comment by lapwat** [comment]
Thanks for the files
